// iOS PWA launch-screen (splash) images. iOS only honours an
// apple-touch-startup-image whose dimensions exactly match the device, so we
// emit one media-queried <link> per common iPhone resolution. The PNGs (the new
// ClearOff glyph centred on the manifest background) are generated by
// scripts/gen-ios-splash.mjs — re-run it if the brand glyph changes.
//
// React 19 hoists these <link> tags into <head> automatically.

const SPLASH_LINKS: { media: string; href: string }[] = [
  { media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)", href: "/splash/apple-splash-640x1136.png" },
  { media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)", href: "/splash/apple-splash-750x1334.png" },
  { media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1242x2208.png" },
  { media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1125x2436.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)", href: "/splash/apple-splash-828x1792.png" },
  { media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1242x2688.png" },
  { media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1170x2532.png" },
  { media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1284x2778.png" },
  { media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1179x2556.png" },
  { media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1290x2796.png" },
  { media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)", href: "/splash/apple-splash-1206x2622.png" },
];

export function IOSSplashLinks() {
  return (
    <>
      {SPLASH_LINKS.map((l) => (
        <link key={l.href} rel="apple-touch-startup-image" media={l.media} href={l.href} />
      ))}
    </>
  );
}
